-- =====================================================================
-- POLYGATE — MYSQL CANONICAL RELATIONAL SCHEMA (DDL)
-- =====================================================================
-- Conventions:
--   * Table prefix "PG_" to avoid collisions in shared schemas.
--   * Surrogate identity primary keys using AUTO_INCREMENT.
--   * CREATED_AT / UPDATED_AT on every table for auditability.
--   * Secrets are stored as BLOB and are expected to be AES-256-GCM encrypted.
--   * ALL tables, columns, constraints, and index names are in UPPERCASE.
-- =====================================================================

-- ---------------------------------------------------------------------
-- PG_APPLICATION_DOMAIN: Lookup for domain type / category
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_DOMAIN (
    DOMAIN_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOMAIN_CODE  VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_DOMAIN_CODE UNIQUE (DOMAIN_CODE)
);

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_PURPOSE: Lookup for endpoint purpose / operation type
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_PURPOSE (
    PURPOSE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    PURPOSE_CODE VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_PURPOSE_CODE UNIQUE (PURPOSE_CODE)
);

-- ---------------------------------------------------------------------
-- PG_AUDIT_ACTION: Lookup for auditable actions
-- ---------------------------------------------------------------------
CREATE TABLE PG_AUDIT_ACTION (
    ACTION_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTION_CODE  VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_ACTION_CODE UNIQUE (ACTION_CODE)
);

-- ---------------------------------------------------------------------
-- PG_PERSON: Represents physical users owning identities
-- ---------------------------------------------------------------------
CREATE TABLE PG_PERSON (
    PERSON_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    EMAIL        VARCHAR(256) NOT NULL,
    STATUS       VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_PERSON_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_PG_PERSON_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

-- ---------------------------------------------------------------------
-- PG_APPLICATION: Main application registry referencing domain type
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION (
    APP_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    APP_KEY      VARCHAR(64) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    DOMAIN_ID    BIGINT NOT NULL,
    AUTH_TYPE    VARCHAR(32) NOT NULL,
    STATUS       VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_APP_KEY UNIQUE (APP_KEY),
    CONSTRAINT FK_PG_APP_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES PG_APPLICATION_DOMAIN(DOMAIN_ID),
    CONSTRAINT CK_PG_APP_AUTH_TYPE CHECK (AUTH_TYPE IN ('OAUTH', 'BASIC', 'API_KEY', 'NONE')),
    CONSTRAINT CK_PG_APP_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

-- ---------------------------------------------------------------------
-- PG_APPLICATION_SUBSCRIPTION: Subscription/plan tiers
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_SUBSCRIPTION (
    SUBSCRIPTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    APP_ID          BIGINT NOT NULL,
    PLAN_NAME       VARCHAR(64) NOT NULL,
    STATUS          VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    START_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_DATE        TIMESTAMP NULL,
    RATE_LIMIT_RPS  INT DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_SUB_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PG_SUB_STATUS CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'SUSPENDED'))
);

-- ---------------------------------------------------------------------
-- PG_APP_ACCESS_CHANNEL: Multi-audience endpoint access channels
-- ---------------------------------------------------------------------
CREATE TABLE PG_APP_ACCESS_CHANNEL (
    CHANNEL_ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    APP_ID                    BIGINT NOT NULL,
    CHANNEL_TYPE              VARCHAR(32) NOT NULL,
    BASE_URL                  VARCHAR(512) NOT NULL,
    LOGIN_URL                 VARCHAR(512),
    LOGOUT_URL                VARCHAR(512),
    LOGIN_SUCCESS_URL_PATTERN VARCHAR(256),
    LOGIN_SUCCESS_COOKIE_NAME VARCHAR(256),
    SESSION_INJECTION_RULES   JSON,
    USER_ID_COOKIE_NAME       VARCHAR(128),
    SESSION_CAPTURE_HEADERS   VARCHAR(256),
    CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_CHANNEL_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_APP_CHANNEL UNIQUE (APP_ID, CHANNEL_TYPE),
    CONSTRAINT CK_PG_CHANNEL_TYPE CHECK (CHANNEL_TYPE IN ('CUSTOMER', 'BROKER', 'PARTNER', 'INTERNAL'))
);

-- ---------------------------------------------------------------------
-- PG_APPLICATION_VERSION: Subscription/channel API versioning
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_VERSION (
    VERSION_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHANNEL_ID     BIGINT NOT NULL,
    VERSION_LABEL  VARCHAR(32) NOT NULL,
    EFFECTIVE_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EFFECTIVE_TO   TIMESTAMP NULL,
    IS_CURRENT     TINYINT(1) DEFAULT 1 NOT NULL,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_VER_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES PG_APP_ACCESS_CHANNEL(CHANNEL_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_CHANNEL_VERSION UNIQUE (CHANNEL_ID, VERSION_LABEL),
    CONSTRAINT CK_PG_VERSION_EFF CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);

-- Note: MySQL unique index ensuring at most one current version per channel
CREATE UNIQUE INDEX IDX_UQ_VER_CURRENT_CHANNEL ON PG_APPLICATION_VERSION (CHANNEL_ID, (CASE WHEN IS_CURRENT = 1 THEN 1 ELSE NULL END));

-- ---------------------------------------------------------------------
-- PG_USER_IDENTITY: Login identity for a person per application
-- ---------------------------------------------------------------------
CREATE TABLE PG_USER_IDENTITY (
    IDENTITY_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID        BIGINT NOT NULL,
    APP_ID           BIGINT NOT NULL,
    USER_ID          VARCHAR(128) NOT NULL,
    AUTH_CREDENTIALS BLOB,
    KEY_VERSION      SMALLINT NOT NULL,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    -- CASCADE FK REVIEW: ON DELETE CASCADE is intentional to fully clear identities on application delete.
    CONSTRAINT FK_PG_IDENT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PG_PERSON(PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PG_IDENT_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_APP_USER UNIQUE (APP_ID, USER_ID)
);

-- ---------------------------------------------------------------------
-- PG_SESSION_CREDENTIAL: Captured sessions per identity
-- ---------------------------------------------------------------------
CREATE TABLE PG_SESSION_CREDENTIAL (
    SESSION_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    IDENTITY_ID    BIGINT NOT NULL,
    COOKIE_PAYLOAD BLOB NOT NULL,
    HEADER_PAYLOAD BLOB NOT NULL,
    KEY_VERSION    SMALLINT NOT NULL,
    SESSION_UUID   VARCHAR(36) NOT NULL,
    CAPTURED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT     TIMESTAMP NULL,
    IS_ACTIVE      TINYINT(1) DEFAULT 1 NOT NULL,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    -- CASCADE FK REVIEW: ON DELETE CASCADE is intentional to clear sessions when user identity is removed.
    CONSTRAINT FK_PG_SESSION_IDENTITY FOREIGN KEY (IDENTITY_ID) REFERENCES PG_USER_IDENTITY(IDENTITY_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_SESSION_UUID UNIQUE (SESSION_UUID),
    CONSTRAINT CK_PG_SESSION_EXP CHECK (EXPIRES_AT IS NULL OR EXPIRES_AT > CAPTURED_AT)
);

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_DEFINITION: Endpoint definition supporting HTTP or WS
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_DEFINITION (
    ENDPOINT_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION_ID           BIGINT NOT NULL,
    NAME                 VARCHAR(128) NOT NULL,
    PURPOSE_ID           BIGINT NOT NULL,
    PROTOCOL_TYPE        VARCHAR(16) NOT NULL,
    PATH                 VARCHAR(512),
    HTTP_METHOD          VARCHAR(8),
    WS_URL_PATH          VARCHAR(512),
    WS_SUBPROTOCOL       VARCHAR(128),
    WS_MESSAGE_SCHEMA    JSON,
    REQUIRES_AUTH        TINYINT(1) DEFAULT 1 NOT NULL,
    REQUEST_HEADERS      TEXT,
    REQUEST_BODY_SCHEMA  JSON,
    RESPONSE_BODY_SCHEMA JSON,
    SAMPLE_RESPONSE      TEXT,
    DESCRIPTION          VARCHAR(1024),
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_ENDPOINT_VERSION FOREIGN KEY (VERSION_ID) REFERENCES PG_APPLICATION_VERSION(VERSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PG_ENDPOINT_PURPOSE FOREIGN KEY (PURPOSE_ID) REFERENCES PG_ENDPOINT_PURPOSE(PURPOSE_ID),
    CONSTRAINT UQ_PG_VERSION_ENDPOINT UNIQUE (VERSION_ID, NAME),
    CONSTRAINT CK_PG_ENDPOINT_PROTOCOL CHECK (PROTOCOL_TYPE IN ('HTTP', 'WEBSOCKET')),
    CONSTRAINT CK_PG_ENDPOINT_METHOD CHECK (HTTP_METHOD IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')),
    CONSTRAINT CK_PG_ENDPOINT_PROTO_CON CHECK (
        (PROTOCOL_TYPE = 'HTTP' AND PATH IS NOT NULL AND HTTP_METHOD IS NOT NULL) OR
        (PROTOCOL_TYPE = 'WEBSOCKET' AND WS_URL_PATH IS NOT NULL)
    )
);

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_RESPONSE_STATUS: Available response codes per endpoint
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_RESPONSE_STATUS (
    STATUS_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    ENDPOINT_ID BIGINT NOT NULL,
    STATUS_CODE INT NOT NULL,
    MEANING     VARCHAR(256) NOT NULL,
    IS_SUCCESS  TINYINT(1) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_STATUS_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_ENDPOINT_STATUS UNIQUE (ENDPOINT_ID, STATUS_CODE)
);

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_PARAMETER: Validation, static and dynamic parameter routing
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_PARAMETER (
    PARAMETER_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ENDPOINT_ID          BIGINT NOT NULL,
    PARAM_NAME           VARCHAR(128) NOT NULL,
    LOCATION             VARCHAR(32) NOT NULL,
    DATA_TYPE            VARCHAR(32) NOT NULL,
    IS_REQUIRED          TINYINT(1) DEFAULT 1 NOT NULL,
    DEFAULT_STATIC_VALUE TEXT,
    IS_DYNAMIC           TINYINT(1) DEFAULT 1 NOT NULL,
    IS_INTERNAL_ONLY     TINYINT(1) DEFAULT 0 NOT NULL,
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_PARAM_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_ENDPOINT_PARAM UNIQUE (ENDPOINT_ID, PARAM_NAME, LOCATION),
    CONSTRAINT CK_PG_PARAM_LOCATION CHECK (LOCATION IN ('PATH', 'QUERY', 'HEADER', 'BODY'))
);

-- ---------------------------------------------------------------------
-- PG_AUDIT_LOG: Audit trailing and multi-tier transaction tracing
-- ---------------------------------------------------------------------
-- Partitioning Rationale:
-- Range partitioning by monthly intervals on EXECUTED_AT allows efficient log rotation.
CREATE TABLE PG_AUDIT_LOG (
    LOG_ID         BIGINT AUTO_INCREMENT,
    APP_ID         BIGINT,
    ENDPOINT_ID    BIGINT,
    PERSON_ID      BIGINT,
    IDENTITY_ID    BIGINT,
    SESSION_ID     BIGINT,
    ACTION_ID      BIGINT NOT NULL,
    STATUS_CODE    INT,
    CORRELATION_ID VARCHAR(64),
    DETAIL         TEXT,
    EXECUTED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (LOG_ID, EXECUTED_AT),
    CONSTRAINT FK_PG_AUDIT_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PG_PERSON(PERSON_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_IDENTITY FOREIGN KEY (IDENTITY_ID) REFERENCES PG_USER_IDENTITY(IDENTITY_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES PG_SESSION_CREDENTIAL(SESSION_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_ACTION FOREIGN KEY (ACTION_ID) REFERENCES PG_AUDIT_ACTION(ACTION_ID)
) PARTITION BY RANGE (TO_DAYS(EXECUTED_AT)) (
    PARTITION P_202607 VALUES LESS THAN (TO_DAYS('2026-08-01')),
    PARTITION P_202608 VALUES LESS THAN (TO_DAYS('2026-09-01')),
    PARTITION P_MAX VALUES LESS THAN MAXVALUE
);

-- ---------------------------------------------------------------------
-- MYSQL INDEXES
-- ---------------------------------------------------------------------
CREATE INDEX IDX_PG_APP_DOMAIN ON PG_APPLICATION(DOMAIN_ID);
CREATE INDEX IDX_PG_SUB_APP ON PG_APPLICATION_SUBSCRIPTION(APP_ID);
CREATE INDEX IDX_PG_CHANNEL_APP ON PG_APP_ACCESS_CHANNEL(APP_ID);
CREATE INDEX IDX_PG_VER_CHANNEL ON PG_APPLICATION_VERSION(CHANNEL_ID);
CREATE INDEX IDX_PG_IDENT_PERSON ON PG_USER_IDENTITY(PERSON_ID);
CREATE INDEX IDX_PG_IDENT_APP ON PG_USER_IDENTITY(APP_ID);
CREATE INDEX IDX_PG_SESSION_IDENTITY ON PG_SESSION_CREDENTIAL(IDENTITY_ID);
CREATE INDEX IDX_PG_ENDPOINT_VERSION ON PG_ENDPOINT_DEFINITION(VERSION_ID);
CREATE INDEX IDX_PG_ENDPOINT_PURPOSE ON PG_ENDPOINT_DEFINITION(PURPOSE_ID);
CREATE INDEX IDX_PG_STATUS_ENDPOINT ON PG_ENDPOINT_RESPONSE_STATUS(ENDPOINT_ID);
CREATE INDEX IDX_PG_PARAM_ENDPOINT ON PG_ENDPOINT_PARAMETER(ENDPOINT_ID);

-- Performance & Lookup Indexes (Requirement 5)
CREATE INDEX IDX_PG_PERSON_IDENTITY ON PG_USER_IDENTITY(PERSON_ID, APP_ID);
CREATE INDEX IDX_PG_IDENTITY_SESSION ON PG_SESSION_CREDENTIAL(IDENTITY_ID, IS_ACTIVE);
CREATE INDEX IDX_PG_AUDIT_CORRELATION ON PG_AUDIT_LOG(CORRELATION_ID);
CREATE INDEX IDX_PG_AUDIT_EXECUTED ON PG_AUDIT_LOG(EXECUTED_AT);
CREATE INDEX IDX_PG_AUDIT_PERSON ON PG_AUDIT_LOG(PERSON_ID);
CREATE INDEX IDX_PG_AUDIT_IDENTITY ON PG_AUDIT_LOG(IDENTITY_ID);
