-- =====================================================================
-- POLYGATE — CANONICAL RELATIONAL SCHEMA
-- =====================================================================
-- This canonical DDL provides both PostgreSQL and Oracle Database schema
-- implementations for PolyGate. The in-memory, YAML, and Oracle persistence
-- adapters mirror this shape.
--
-- Conventions:
--   * Table prefix "PG_" to avoid collisions in shared schemas.
--   * Surrogate identity primary keys.
--   * CREATED_AT / UPDATED_AT on every table for auditability.
--   * Secrets are stored as BYTEA/BLOB and are expected to be AES-256-GCM encrypted.
--   * ALL tables, columns, constraints, and index names are in UPPERCASE.
-- =====================================================================

-- =====================================================================
-- BLOCK 1: POSTGRESQL IMPLEMENTATION
-- =====================================================================

-- Shared trigger function for updating UPDATED_AT timestamp
CREATE OR REPLACE FUNCTION FN_SET_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

-- ---------------------------------------------------------------------
-- PG_APPLICATION_DOMAIN: Lookup for domain type / category
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_DOMAIN (
    DOMAIN_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOMAIN_CODE  VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_DOMAIN_CODE UNIQUE (DOMAIN_CODE)
);

COMMENT ON TABLE  PG_APPLICATION_DOMAIN IS 'Lookup table for target application category types (e.g. HOTEL, AIRLINE, BROKER).';
COMMENT ON COLUMN PG_APPLICATION_DOMAIN.DOMAIN_ID IS 'Surrogate identity primary key for the domain category.';
COMMENT ON COLUMN PG_APPLICATION_DOMAIN.DOMAIN_CODE IS 'Unique short code identifying the domain category.';
COMMENT ON COLUMN PG_APPLICATION_DOMAIN.DISPLAY_NAME IS 'Human-readable display name of the domain category.';
COMMENT ON COLUMN PG_APPLICATION_DOMAIN.CREATED_AT IS 'Timestamp when the domain category was created.';
COMMENT ON COLUMN PG_APPLICATION_DOMAIN.UPDATED_AT IS 'Timestamp when the domain category was last updated.';

CREATE TRIGGER TRG_PG_APP_DOMAIN_UPDATED
BEFORE UPDATE ON PG_APPLICATION_DOMAIN
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_PURPOSE: Lookup for endpoint purpose / operation type
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_PURPOSE (
    PURPOSE_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PURPOSE_CODE VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_PURPOSE_CODE UNIQUE (PURPOSE_CODE)
);

COMMENT ON TABLE  PG_ENDPOINT_PURPOSE IS 'Lookup table for target endpoint purposes (e.g. LOGIN, LOGOUT, VERIFY, CREATE, READ, UPDATE, DELETE, LIST).';
COMMENT ON COLUMN PG_ENDPOINT_PURPOSE.PURPOSE_ID IS 'Surrogate identity primary key for the endpoint purpose.';
COMMENT ON COLUMN PG_ENDPOINT_PURPOSE.PURPOSE_CODE IS 'Unique short code identifying the endpoint purpose.';
COMMENT ON COLUMN PG_ENDPOINT_PURPOSE.DISPLAY_NAME IS 'Human-readable display name of the endpoint purpose.';
COMMENT ON COLUMN PG_ENDPOINT_PURPOSE.CREATED_AT IS 'Timestamp when the endpoint purpose was created.';
COMMENT ON COLUMN PG_ENDPOINT_PURPOSE.UPDATED_AT IS 'Timestamp when the endpoint purpose was last updated.';

CREATE TRIGGER TRG_PG_ENDPOINT_PURPOSE_UPDATED
BEFORE UPDATE ON PG_ENDPOINT_PURPOSE
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_AUDIT_ACTION: Lookup for auditable actions
-- ---------------------------------------------------------------------
CREATE TABLE PG_AUDIT_ACTION (
    ACTION_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACTION_CODE  VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_ACTION_CODE UNIQUE (ACTION_CODE)
);

COMMENT ON TABLE  PG_AUDIT_ACTION IS 'Lookup table for auditable actions performed (e.g. LOGIN, LOGOUT, VERIFY, PROXY, SEED, ORDER_CREATE, ORDER_READ, ORDER_UPDATE, ORDER_DELETE, ORDER_LIST).';
COMMENT ON COLUMN PG_AUDIT_ACTION.ACTION_ID IS 'Surrogate identity primary key for the audit action.';
COMMENT ON COLUMN PG_AUDIT_ACTION.ACTION_CODE IS 'Unique short code identifying the audit action.';
COMMENT ON COLUMN PG_AUDIT_ACTION.DISPLAY_NAME IS 'Human-readable display name of the audit action.';
COMMENT ON COLUMN PG_AUDIT_ACTION.CREATED_AT IS 'Timestamp when the audit action was created.';
COMMENT ON COLUMN PG_AUDIT_ACTION.UPDATED_AT IS 'Timestamp when the audit action was last updated.';

CREATE TRIGGER TRG_PG_AUDIT_ACTION_UPDATED
BEFORE UPDATE ON PG_AUDIT_ACTION
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_PERSON: Represents physical users owning identities
-- ---------------------------------------------------------------------
CREATE TABLE PG_PERSON (
    PERSON_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    EMAIL        VARCHAR(256) NOT NULL,
    STATUS       VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_PERSON_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_PG_PERSON_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

COMMENT ON TABLE  PG_PERSON IS 'Represents a real person/user owning one or more access identities across applications.';
COMMENT ON COLUMN PG_PERSON.PERSON_ID IS 'Surrogate identity primary key for the person.';
COMMENT ON COLUMN PG_PERSON.DISPLAY_NAME IS 'Human-readable display name of the person.';
COMMENT ON COLUMN PG_PERSON.EMAIL IS 'Unique email address of the person.';
COMMENT ON COLUMN PG_PERSON.STATUS IS 'Lifecycle state of the person profile (ACTIVE, SUSPENDED, DELETED).';
COMMENT ON COLUMN PG_PERSON.CREATED_AT IS 'Timestamp when the person record was created.';
COMMENT ON COLUMN PG_PERSON.UPDATED_AT IS 'Timestamp when the person record was last updated.';

CREATE TRIGGER TRG_PG_PERSON_UPDATED
BEFORE UPDATE ON PG_PERSON
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_APPLICATION: Main application registry referencing domain type
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION (
    APP_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_KEY      VARCHAR(64) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    DOMAIN_ID    BIGINT NOT NULL,
    AUTH_TYPE    VARCHAR(32) NOT NULL,
    STATUS       VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PG_APP_KEY UNIQUE (APP_KEY),
    CONSTRAINT FK_PG_APP_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES PG_APPLICATION_DOMAIN(DOMAIN_ID),
    CONSTRAINT CK_PG_APP_AUTH_TYPE CHECK (AUTH_TYPE IN ('OAUTH', 'BASIC', 'API_KEY', 'NONE')),
    CONSTRAINT CK_PG_APP_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

COMMENT ON TABLE  PG_APPLICATION IS 'Registered downstream target applications grouped by domain category.';
COMMENT ON COLUMN PG_APPLICATION.APP_ID IS 'Surrogate identity primary key for the application.';
COMMENT ON COLUMN PG_APPLICATION.APP_KEY IS 'Short identifier used in routes, e.g. /apps/copilot';
COMMENT ON COLUMN PG_APPLICATION.DISPLAY_NAME IS 'Human-readable name of the application.';
COMMENT ON COLUMN PG_APPLICATION.DOMAIN_ID IS 'Foreign key reference to PG_APPLICATION_DOMAIN.';
COMMENT ON COLUMN PG_APPLICATION.AUTH_TYPE IS 'Authentication mechanism category (OAUTH, BASIC, API_KEY, NONE).';
COMMENT ON COLUMN PG_APPLICATION.STATUS IS 'Operational status of the application mapping (ACTIVE, DISABLED).';
COMMENT ON COLUMN PG_APPLICATION.CREATED_AT IS 'Timestamp when the application record was created.';
COMMENT ON COLUMN PG_APPLICATION.UPDATED_AT IS 'Timestamp when the application record was last updated.';

CREATE TRIGGER TRG_PG_APPLICATION_UPDATED
BEFORE UPDATE ON PG_APPLICATION
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_APPLICATION_SUBSCRIPTION: Subscription/plan tiers
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_SUBSCRIPTION (
    SUBSCRIPTION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID          BIGINT NOT NULL,
    PLAN_NAME       VARCHAR(64) NOT NULL,
    STATUS          VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL,
    START_DATE      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_DATE        TIMESTAMP WITH TIME ZONE,
    RATE_LIMIT_RPS  INTEGER DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_SUB_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PG_SUB_STATUS CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'SUSPENDED'))
);

COMMENT ON TABLE  PG_APPLICATION_SUBSCRIPTION IS 'Subscription plan metadata affecting access rights and rate limits per application.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.SUBSCRIPTION_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.APP_ID IS 'Foreign key reference to PG_APPLICATION.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.PLAN_NAME IS 'Subscription tier name (e.g., GOLD, SILVER, PLATINUM).';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.STATUS IS 'Operational subscription status (ACTIVE, EXPIRED, SUSPENDED).';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.START_DATE IS 'Activation timestamp of the subscription tier.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.END_DATE IS 'Expiry timestamp of the subscription tier (nullable if perpetual).';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.RATE_LIMIT_RPS IS 'Enforced requests-per-second rate limit for the subscription.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.CREATED_AT IS 'Timestamp when the subscription was recorded.';
COMMENT ON COLUMN PG_APPLICATION_SUBSCRIPTION.UPDATED_AT IS 'Timestamp when the subscription record was updated.';

CREATE TRIGGER TRG_PG_SUBSCRIPTION_UPDATED
BEFORE UPDATE ON PG_APPLICATION_SUBSCRIPTION
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_APP_ACCESS_CHANNEL: Multi-audience endpoint access channels
-- ---------------------------------------------------------------------
CREATE TABLE PG_APP_ACCESS_CHANNEL (
    CHANNEL_ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID                    BIGINT NOT NULL,
    CHANNEL_TYPE              VARCHAR(32) NOT NULL,
    BASE_URL                  VARCHAR(512) NOT NULL,
    LOGIN_URL                 VARCHAR(512),
    LOGOUT_URL                VARCHAR(512),
    LOGIN_SUCCESS_URL_PATTERN VARCHAR(256),
    LOGIN_SUCCESS_COOKIE_NAME VARCHAR(256),
    SESSION_INJECTION_RULES   JSONB,
    USER_ID_COOKIE_NAME       VARCHAR(128),
    CREATED_AT                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_CHANNEL_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_APP_CHANNEL UNIQUE (APP_ID, CHANNEL_TYPE),
    CONSTRAINT CK_PG_CHANNEL_TYPE CHECK (CHANNEL_TYPE IN ('CUSTOMER', 'BROKER', 'PARTNER', 'INTERNAL'))
);

COMMENT ON TABLE  PG_APP_ACCESS_CHANNEL IS 'Distinct entry points, URLs, and browser capture configuration for an application per target audience.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.CHANNEL_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.APP_ID IS 'Foreign key reference to PG_APPLICATION.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.CHANNEL_TYPE IS 'Target audience category (CUSTOMER, BROKER, PARTNER, INTERNAL).';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.BASE_URL IS 'Upstream destination base URL of the channel.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.LOGIN_URL IS 'Upstream login landing page for this channel.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.LOGOUT_URL IS 'Upstream logout landing page for this channel.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.LOGIN_SUCCESS_URL_PATTERN IS 'Regex pattern matched against browser URLs to signal a successful login capture.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.LOGIN_SUCCESS_COOKIE_NAME IS 'The cookie name that indicates authenticated session readiness.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.SESSION_INJECTION_RULES IS 'JSON structure containing cookie/header injection rules during proxying.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.USER_ID_COOKIE_NAME IS 'Cookie used to extract the user identifier for tenancy logic.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.CREATED_AT IS 'Timestamp when the channel was created.';
COMMENT ON COLUMN PG_APP_ACCESS_CHANNEL.UPDATED_AT IS 'Timestamp when the channel was last updated.';

CREATE TRIGGER TRG_PG_ACCESS_CHANNEL_UPDATED
BEFORE UPDATE ON PG_APP_ACCESS_CHANNEL
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_APPLICATION_VERSION: Subscription/channel API versioning
-- ---------------------------------------------------------------------
CREATE TABLE PG_APPLICATION_VERSION (
    VERSION_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHANNEL_ID     BIGINT NOT NULL,
    VERSION_LABEL  VARCHAR(32) NOT NULL,
    EFFECTIVE_FROM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EFFECTIVE_TO   TIMESTAMP WITH TIME ZONE,
    IS_CURRENT     BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_VER_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES PG_APP_ACCESS_CHANNEL(CHANNEL_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_CHANNEL_VERSION UNIQUE (CHANNEL_ID, VERSION_LABEL),
    CONSTRAINT CK_PG_VERSION_EFF CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);

COMMENT ON TABLE  PG_APPLICATION_VERSION IS 'Version lifecycle tracking for API definitions per application channel.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.VERSION_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.CHANNEL_ID IS 'Foreign key reference to PG_APP_ACCESS_CHANNEL.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.VERSION_LABEL IS 'Human friendly label of the version (e.g. v1, v2.1).';
COMMENT ON COLUMN PG_APPLICATION_VERSION.EFFECTIVE_FROM IS 'Activation timestamp of the version.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.EFFECTIVE_TO IS 'Deactivation timestamp of the version (nullable if active).';
COMMENT ON COLUMN PG_APPLICATION_VERSION.IS_CURRENT IS 'Flag indicating whether this version is the current active channel definition.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.CREATED_AT IS 'Timestamp when the version record was created.';
COMMENT ON COLUMN PG_APPLICATION_VERSION.UPDATED_AT IS 'Timestamp when the version record was last updated.';

CREATE TRIGGER TRG_PG_APPLICATION_VERSION_UPDATED
BEFORE UPDATE ON PG_APPLICATION_VERSION
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- Partial unique index ensuring at most one current version per channel
CREATE UNIQUE INDEX IDX_UQ_VER_CURRENT_CHANNEL ON PG_APPLICATION_VERSION (CHANNEL_ID) WHERE IS_CURRENT = TRUE;

-- ---------------------------------------------------------------------
-- PG_USER_IDENTITY: Login identity for a person per application
-- ---------------------------------------------------------------------
CREATE TABLE PG_USER_IDENTITY (
    IDENTITY_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERSON_ID        BIGINT NOT NULL,
    APP_ID           BIGINT NOT NULL,
    USER_ID          VARCHAR(128) NOT NULL,
    AUTH_CREDENTIALS BYTEA,
    KEY_VERSION      SMALLINT NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- CASCADE FK REVIEW: ON DELETE CASCADE is intentional to fully clear identities on application delete.
    CONSTRAINT FK_PG_IDENT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PG_PERSON(PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PG_IDENT_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_APP_USER UNIQUE (APP_ID, USER_ID)
);

COMMENT ON TABLE  PG_USER_IDENTITY IS 'Unique credentials and identities held by a person on a specific application.';
COMMENT ON COLUMN PG_USER_IDENTITY.IDENTITY_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_USER_IDENTITY.PERSON_ID IS 'Foreign key reference to PG_PERSON (the owner).';
COMMENT ON COLUMN PG_USER_IDENTITY.APP_ID IS 'Foreign key reference to PG_APPLICATION.';
COMMENT ON COLUMN PG_USER_IDENTITY.USER_ID IS 'Login username/identifier specific to the application.';
COMMENT ON COLUMN PG_USER_IDENTITY.AUTH_CREDENTIALS IS 'AES-256-GCM encrypted binary payload containing OAuth tokens or credentials.';
COMMENT ON COLUMN PG_USER_IDENTITY.KEY_VERSION IS 'Encryption key version used to decrypt credentials, enabling key rotation.';
COMMENT ON COLUMN PG_USER_IDENTITY.CREATED_AT IS 'Timestamp when this user identity was created.';
COMMENT ON COLUMN PG_USER_IDENTITY.UPDATED_AT IS 'Timestamp when this user identity was last updated.';

CREATE TRIGGER TRG_PG_USER_IDENTITY_UPDATED
BEFORE UPDATE ON PG_USER_IDENTITY
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_SESSION_CREDENTIAL: Captured sessions per identity
-- ---------------------------------------------------------------------
CREATE TABLE PG_SESSION_CREDENTIAL (
    SESSION_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTITY_ID    BIGINT NOT NULL,
    COOKIE_PAYLOAD BYTEA NOT NULL,
    HEADER_PAYLOAD BYTEA NOT NULL,
    KEY_VERSION    SMALLINT NOT NULL,
    SESSION_UUID   UUID NOT NULL,
    CAPTURED_AT    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT     TIMESTAMP WITH TIME ZONE,
    IS_ACTIVE      BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- CASCADE FK REVIEW: ON DELETE CASCADE is intentional to clear sessions when user identity is removed.
    CONSTRAINT FK_PG_SESSION_IDENTITY FOREIGN KEY (IDENTITY_ID) REFERENCES PG_USER_IDENTITY(IDENTITY_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_SESSION_UUID UNIQUE (SESSION_UUID),
    CONSTRAINT CK_PG_SESSION_EXP CHECK (EXPIRES_AT IS NULL OR EXPIRES_AT > CAPTURED_AT)
);

COMMENT ON TABLE  PG_SESSION_CREDENTIAL IS 'Encrypted session tokens/cookies captured for a specific application identity.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.SESSION_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.IDENTITY_ID IS 'Foreign key reference to PG_USER_IDENTITY.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.COOKIE_PAYLOAD IS 'AES-256-GCM encrypted, serialized cookie jar binary payload.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.HEADER_PAYLOAD IS 'AES-256-GCM encrypted, serialized header map binary payload.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.KEY_VERSION IS 'Encryption key version used to decrypt cookies and headers, enabling key rotation.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.SESSION_UUID IS 'Unique session lookup UUID identifier exposed to clients.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.CAPTURED_AT IS 'Timestamp when the credentials were captured.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.EXPIRES_AT IS 'Optional expiration timestamp of the session credentials.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.IS_ACTIVE IS 'Binary indicator representing session validity state.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.CREATED_AT IS 'Timestamp when the record was created.';
COMMENT ON COLUMN PG_SESSION_CREDENTIAL.UPDATED_AT IS 'Timestamp when the record was last updated.';

CREATE TRIGGER TRG_PG_SESSION_CREDENTIAL_UPDATED
BEFORE UPDATE ON PG_SESSION_CREDENTIAL
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_DEFINITION: Endpoint definition supporting HTTP or WS
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_DEFINITION (
    ENDPOINT_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VERSION_ID           BIGINT NOT NULL,
    NAME                 VARCHAR(128) NOT NULL,
    PURPOSE_ID           BIGINT NOT NULL,
    PROTOCOL_TYPE        VARCHAR(16) NOT NULL,
    PATH                 VARCHAR(512),
    HTTP_METHOD          VARCHAR(8),
    WS_URL_PATH          VARCHAR(512),
    WS_SUBPROTOCOL       VARCHAR(128),
    WS_MESSAGE_SCHEMA    JSONB,
    REQUIRES_AUTH        BOOLEAN DEFAULT TRUE NOT NULL,
    REQUEST_HEADERS      TEXT,
    REQUEST_BODY_SCHEMA  JSONB,
    RESPONSE_BODY_SCHEMA JSONB,
    SAMPLE_RESPONSE      TEXT,
    DESCRIPTION          VARCHAR(1024),
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_ENDPOINT_VERSION FOREIGN KEY (VERSION_ID) REFERENCES PG_APPLICATION_VERSION(VERSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PG_ENDPOINT_PURPOSE FOREIGN KEY (PURPOSE_ID) REFERENCES PG_ENDPOINT_PURPOSE(PURPOSE_ID),
    CONSTRAINT UQ_PG_VERSION_ENDPOINT UNIQUE (VERSION_ID, NAME),
    CONSTRAINT CK_PG_ENDPOINT_PROTOCOL CHECK (PROTOCOL_TYPE IN ('HTTP', 'WEBSOCKET')),
    CONSTRAINT CK_PG_ENDPOINT_METHOD CHECK (HTTP_METHOD IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')),
    CONSTRAINT CK_PG_ENDPOINT_PROTO_CON CHECK (
        (PROTOCOL_TYPE = 'HTTP' AND PATH IS NOT NULL AND HTTP_METHOD IS NOT NULL) OR
        (PROTOCOL_TYPE = 'WEBSOCKET' AND WS_URL_PATH IS NOT NULL)
    )
);

COMMENT ON TABLE  PG_ENDPOINT_DEFINITION IS 'Registered application endpoints, supporting either HTTP or WebSocket protocol, mapped to version constraints.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.ENDPOINT_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.VERSION_ID IS 'Foreign key reference to PG_APPLICATION_VERSION.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.NAME IS 'Unique developer friendly endpoint name.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.PURPOSE_ID IS 'Foreign key reference to PG_ENDPOINT_PURPOSE.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.PROTOCOL_TYPE IS 'Operational network protocol (HTTP, WEBSOCKET).';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.PATH IS 'Path route suffix of the endpoint (HTTP-only).';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.HTTP_METHOD IS 'HTTP verb required (HTTP-only).';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.WS_URL_PATH IS 'WebSocket connection URL path route.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.WS_SUBPROTOCOL IS 'WebSocket connection subprotocol requirements (nullable).';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.WS_MESSAGE_SCHEMA IS 'WebSocket payload frame JSON schemas.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.REQUIRES_AUTH IS 'Boolean flag indicating if proxy routing requires injecting session credentials.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.REQUEST_HEADERS IS 'Serialized JSON list of expected request headers.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.REQUEST_BODY_SCHEMA IS 'JSON Schema describing the request body structure.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.RESPONSE_BODY_SCHEMA IS 'JSON Schema describing the response body structure.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.SAMPLE_RESPONSE IS 'JSON string representing a typical successful response body.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.DESCRIPTION IS 'Documentation summary detailing parameter meanings.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.CREATED_AT IS 'Timestamp when the endpoint was created.';
COMMENT ON COLUMN PG_ENDPOINT_DEFINITION.UPDATED_AT IS 'Timestamp when the endpoint was last updated.';

CREATE TRIGGER TRG_PG_ENDPOINT_DEFINITION_UPDATED
BEFORE UPDATE ON PG_ENDPOINT_DEFINITION
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_RESPONSE_STATUS: Available response codes per endpoint
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_RESPONSE_STATUS (
    STATUS_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENDPOINT_ID BIGINT NOT NULL,
    STATUS_CODE INTEGER NOT NULL,
    MEANING     VARCHAR(256) NOT NULL,
    IS_SUCCESS  BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_STATUS_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_ENDPOINT_STATUS UNIQUE (ENDPOINT_ID, STATUS_CODE)
);

COMMENT ON TABLE  PG_ENDPOINT_RESPONSE_STATUS IS 'Mapping of HTTP status responses and their success classification per endpoint.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.STATUS_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.ENDPOINT_ID IS 'Foreign key reference to PG_ENDPOINT_DEFINITION.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.STATUS_CODE IS 'The HTTP status code (e.g. 200, 201, 400).';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.MEANING IS 'Description of what this status code implies.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.IS_SUCCESS IS 'Boolean flag classifying whether this code indicates success.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.CREATED_AT IS 'Timestamp when the status mapping was created.';
COMMENT ON COLUMN PG_ENDPOINT_RESPONSE_STATUS.UPDATED_AT IS 'Timestamp when the status mapping was last updated.';

CREATE TRIGGER TRG_PG_ENDPOINT_RESPONSE_STATUS_UPDATED
BEFORE UPDATE ON PG_ENDPOINT_RESPONSE_STATUS
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_ENDPOINT_PARAMETER: Validation, static and dynamic parameter routing
-- ---------------------------------------------------------------------
CREATE TABLE PG_ENDPOINT_PARAMETER (
    PARAMETER_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENDPOINT_ID          BIGINT NOT NULL,
    PARAM_NAME           VARCHAR(128) NOT NULL,
    LOCATION             VARCHAR(32) NOT NULL,
    DATA_TYPE            VARCHAR(32) NOT NULL,
    IS_REQUIRED          BOOLEAN DEFAULT TRUE NOT NULL,
    DEFAULT_STATIC_VALUE TEXT,
    IS_DYNAMIC           BOOLEAN DEFAULT TRUE NOT NULL,
    IS_INTERNAL_ONLY     BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PG_PARAM_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PG_ENDPOINT_PARAM UNIQUE (ENDPOINT_ID, PARAM_NAME, LOCATION),
    CONSTRAINT CK_PG_PARAM_LOCATION CHECK (LOCATION IN ('PATH', 'QUERY', 'HEADER', 'BODY'))
);

COMMENT ON TABLE  PG_ENDPOINT_PARAMETER IS 'Structured parameter details driving proxy parsing and downstream request formatting.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.PARAMETER_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.ENDPOINT_ID IS 'Foreign key reference to PG_ENDPOINT_DEFINITION.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.PARAM_NAME IS 'The name of the parameter.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.LOCATION IS 'Where the parameter resides (PATH, QUERY, HEADER, BODY).';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.DATA_TYPE IS 'Data type validation format (e.g. string, integer, boolean).';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.IS_REQUIRED IS 'Boolean flag indicating if the parameter is mandatory.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.DEFAULT_STATIC_VALUE IS 'Fallback value used when not supplied, or the fixed value when static.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.IS_DYNAMIC IS 'Boolean flag: TRUE implies caller provides it at runtime, FALSE means static value stored in schema.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.IS_INTERNAL_ONLY IS 'Flag (0/1) indicating that the parameter is for Polygate internal use only. If a parameter is static (IS_DYNAMIC = 0) and internal-only (IS_INTERNAL_ONLY = 1), proxy implementation must redact/strip it from outbound requests forwarded downstream (e.g. internal routing tags, tenant tracking tags, or Polygate-only correlation IDs).';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.CREATED_AT IS 'Timestamp when the parameter was created.';
COMMENT ON COLUMN PG_ENDPOINT_PARAMETER.UPDATED_AT IS 'Timestamp when the parameter was last updated.';

CREATE TRIGGER TRG_PG_ENDPOINT_PARAMETER_UPDATED
BEFORE UPDATE ON PG_ENDPOINT_PARAMETER
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- ---------------------------------------------------------------------
-- PG_AUDIT_LOG: Audit trailing and multi-tier transaction tracing
-- ---------------------------------------------------------------------
-- Partitioning Rationale:
-- PG_AUDIT_LOG will have the highest write volume in PolyGate.
-- Range partitioning by monthly intervals on EXECUTED_AT allows efficient log rotation,
-- fast bulk deletion of expired logs (by dropping partitions instead of running heavy DELETEs),
-- and localized index lookups.
CREATE TABLE PG_AUDIT_LOG (
    LOG_ID         BIGINT GENERATED ALWAYS AS IDENTITY,
    APP_ID         BIGINT,
    ENDPOINT_ID    BIGINT,
    PERSON_ID      BIGINT,
    IDENTITY_ID    BIGINT,
    SESSION_ID     BIGINT,
    ACTION_ID      BIGINT NOT NULL,
    STATUS_CODE    INTEGER,
    CORRELATION_ID VARCHAR(64),
    DETAIL         TEXT,
    EXECUTED_AT    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (LOG_ID, EXECUTED_AT),
    CONSTRAINT FK_PG_AUDIT_APP FOREIGN KEY (APP_ID) REFERENCES PG_APPLICATION(APP_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES PG_ENDPOINT_DEFINITION(ENDPOINT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PG_PERSON(PERSON_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_IDENTITY FOREIGN KEY (IDENTITY_ID) REFERENCES PG_USER_IDENTITY(IDENTITY_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES PG_SESSION_CREDENTIAL(SESSION_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PG_AUDIT_ACTION FOREIGN KEY (ACTION_ID) REFERENCES PG_AUDIT_ACTION(ACTION_ID)
) PARTITION BY RANGE (EXECUTED_AT);

COMMENT ON TABLE  PG_AUDIT_LOG IS 'Traceability log recording operations, requests, response states, and correlations within the gateway.';
COMMENT ON COLUMN PG_AUDIT_LOG.LOG_ID IS 'Surrogate identity primary key.';
COMMENT ON COLUMN PG_AUDIT_LOG.APP_ID IS 'Optional foreign key reference to related application.';
COMMENT ON COLUMN PG_AUDIT_LOG.ENDPOINT_ID IS 'Optional foreign key reference to related endpoint definition.';
COMMENT ON COLUMN PG_AUDIT_LOG.PERSON_ID IS 'Optional foreign key reference to the related physical person.';
COMMENT ON COLUMN PG_AUDIT_LOG.IDENTITY_ID IS 'Optional foreign key reference to the related login identity used.';
COMMENT ON COLUMN PG_AUDIT_LOG.SESSION_ID IS 'Optional foreign key reference to the active session captured/used.';
COMMENT ON COLUMN PG_AUDIT_LOG.ACTION_ID IS 'Foreign key reference to PG_AUDIT_ACTION lookup table.';
COMMENT ON COLUMN PG_AUDIT_LOG.STATUS_CODE IS 'HTTP status code or execution result code of the action.';
COMMENT ON COLUMN PG_AUDIT_LOG.CORRELATION_ID IS 'Trace ID/Correlation ID grouping multiple requests/responses into one execution stream.';
COMMENT ON COLUMN PG_AUDIT_LOG.DETAIL IS 'Supplemental execution detail logs or JSON messages (redacted).';
COMMENT ON COLUMN PG_AUDIT_LOG.EXECUTED_AT IS 'Timestamp when the action occurred.';
COMMENT ON COLUMN PG_AUDIT_LOG.CREATED_AT IS 'Timestamp when the log record was created.';
COMMENT ON COLUMN PG_AUDIT_LOG.UPDATED_AT IS 'Timestamp when the log record was last updated.';

CREATE TRIGGER TRG_PG_AUDIT_LOG_UPDATED
BEFORE UPDATE ON PG_AUDIT_LOG
FOR EACH ROW EXECUTE FUNCTION FN_SET_UPDATED_AT();

-- Setup basic initial Postgres range partitions
CREATE TABLE PG_AUDIT_LOG_Y2026M07 PARTITION OF PG_AUDIT_LOG
    FOR VALUES FROM ('2026-07-01 00:00:00+00') TO ('2026-08-01 00:00:00+00');
CREATE TABLE PG_AUDIT_LOG_Y2026M08 PARTITION OF PG_AUDIT_LOG
    FOR VALUES FROM ('2026-08-01 00:00:00+00') TO ('2026-09-01 00:00:00+00');
CREATE TABLE PG_AUDIT_LOG_DEFAULT PARTITION OF PG_AUDIT_LOG DEFAULT;

-- ---------------------------------------------------------------------
-- POSTGRESQL INDEXES
-- ---------------------------------------------------------------------
CREATE INDEX IDX_PG_APP_DOMAIN ON PG_APPLICATION(DOMAIN_ID);
CREATE INDEX IDX_PG_SUB_APP ON PG_APPLICATION_SUBSCRIPTION(APP_ID);
CREATE INDEX IDX_PG_CHANNEL_APP ON PG_APP_ACCESS_CHANNEL(APP_ID);
CREATE INDEX IDX_PG_VER_CHANNEL ON PG_APPLICATION_VERSION(CHANNEL_ID);
CREATE INDEX IDX_PG_IDENT_PERSON ON PG_USER_IDENTITY(PERSON_ID);
CREATE INDEX IDX_PG_IDENT_APP ON PG_USER_IDENTITY(APP_ID);
CREATE INDEX IDX_PG_SESSION_IDENTITY ON PG_SESSION_CREDENTIAL(IDENTITY_ID);
CREATE INDEX IDX_PG_ENDPOINT_VERSION ON PG_ENDPOINT_DEFINITION(VERSION_ID);
CREATE INDEX IDX_PG_ENDPOINT_PURPOSE ON PG_ENDPOINT_DEFINITION(PURPOSE_ID);
CREATE INDEX IDX_PG_STATUS_ENDPOINT ON PG_ENDPOINT_RESPONSE_STATUS(ENDPOINT_ID);
CREATE INDEX IDX_PG_PARAM_ENDPOINT ON PG_ENDPOINT_PARAMETER(ENDPOINT_ID);

-- Performance & Lookup Indexes (Requirement 5)
CREATE INDEX IDX_PG_PERSON_IDENTITY ON PG_USER_IDENTITY(PERSON_ID, APP_ID);
CREATE INDEX IDX_PG_IDENTITY_SESSION ON PG_SESSION_CREDENTIAL(IDENTITY_ID, IS_ACTIVE);
CREATE INDEX IDX_PG_AUDIT_CORRELATION ON PG_AUDIT_LOG(CORRELATION_ID);
CREATE INDEX IDX_PG_AUDIT_EXECUTED ON PG_AUDIT_LOG(EXECUTED_AT);
CREATE INDEX IDX_PG_AUDIT_PERSON ON PG_AUDIT_LOG(PERSON_ID);
CREATE INDEX IDX_PG_AUDIT_IDENTITY ON PG_AUDIT_LOG(IDENTITY_ID);